### ISSUE TITLE
TGM Plugin Activation Class needs to be updated due to potential XSS vulnerability

### ISSUE THREAD

**Issue by flickster** [cyberchimps/responsivecore#15]
Reference: http://wptavern.com/xss-vulnerability-what-to-do-if-you-buy-or-sell-items-on-themeforest-and-codecanyon

Latest version: 2.5.0-alpha
https://github.com/thomasgriffin/TGM-Plugin-Activation/blob/develop/class-tgm-plugin-activation.php

**Comment by sandeeprhbwsl** [comment]
Plugin has been updated
